name: Cost Evaluation

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  cost_evaluation_job:
    runs-on: ubuntu-latest

    steps:
    - name: Print start message
      run: echo "Starting the Cost Evaluation job..."
      
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Run cost evaluation script
      run: |
        git checkout HEAD~1
        cp cost.txt cost_master.txt
        git checkout -
          
        PR_COST_FILE="cost.txt"
        MASTER_COST_FILE="cost_master.txt"
        
        rm -f cost_tmp.txt
        touch cost_tmp.txt
    
        PR_COST_ARR=($(cat "$PR_COST_FILE"))
        MASTER_COST_ARR=($(cat "$MASTER_COST_FILE"))
    
        for i in ${!PR_COST_ARR[@]}; do
            echo "Comparing line $((i+1)): PR=${PR_COST_ARR[$i]}, Master=${MASTER_COST_ARR[$i]}"
            if [ ${PR_COST_ARR[$i]} -lt ${MASTER_COST_ARR[$i]} ]; then
                echo "Lower cost on PR. Writing ${PR_COST_ARR[$i]} to temp file."
                echo ${PR_COST_ARR[$i]} >> cost_tmp.txt
            else
                echo "Lower cost in Master or costs are equal. Writing ${MASTER_COST_ARR[$i]} to temp file."
                echo ${MASTER_COST_ARR[$i]} >> cost_tmp.txt
            fi
        done
    
        echo "Final content of cost_temp.txt: $(cat cost_tmp.txt)"
    
    - name: Commit and push if needed
      run: |
        mv cost_tmp.txt cost.txt
        echo "Moved temporary file to cost.txt. The updated content is:"
        cat cost.txt
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
       
        git add cost.txt
        echo "Changes have been detected. Committing and pushing..."
        git commit -m 'Update cost.txt after cost improvement'
        git push origin HEAD:master
        echo "Finished pushing changes"
       
        fi
