name: Cost Evaluation

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  cost_evaluation_job:
    runs-on: ubuntu-latest

    steps:
    - name: Print start message
      run: echo "Starting the Cost Evaluation job..."
      
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Run cost evaluation script
      run: |
        git checkout HEAD~1
        cp cost.txt cost_master.txt
        git checkout -
                
        PR_COST_FILE="cost.txt"
        MASTER_COST_FILE="cost_master.txt"
        
        rm -f cost_tmp.txt
        touch cost_tmp.txt
    
        PR_COST_ARR=($(cat "$PR_COST_FILE"))
        MASTER_COST_ARR=($(cat "$MASTER_COST_FILE"))
    
        for i in ${!PR_COST_ARR[@]}; do
            if [ ${PR_COST_ARR[$i]} -lt ${MASTER_COST_ARR[$i]} ]; then
                echo ${PR_COST_ARR[$i]} >> cost_tmp.txt
            else
                echo ${MASTER_COST_ARR[$i]} >> cost_tmp.txt
            fi
        done
    
        mv cost_tmp.txt cost.txt
